import {
  BadgeDollarSign,
  ClipboardList,
  Grid3X3,
  Newspaper,
  LayoutDashboard,
  MessageSquare,
  Percent,
  Settings,
  ShieldCheck,
  KeyRound,
  PackageOpen,
  Shield,
  Users,
  WalletCards,
} from 'lucide-react'

export const adminNavItems = [
  { id: 'admin-overview', label: 'adminNav.overview', path: '/admin', icon: LayoutDashboard },
  { id: 'admin-users', label: 'adminNav.users', path: '/admin/users', icon: Users },
  { id: 'admin-orders', label: 'adminNav.orders', path: '/admin/orders', icon: ClipboardList },
  { id: 'admin-finance', label: 'adminNav.finance', path: '/admin/finance', icon: WalletCards },
  { id: 'admin-tickets', label: 'adminNav.tickets', path: '/admin/tickets', icon: MessageSquare },
  { id: 'admin-services', label: 'adminNav.services', path: '/admin/services', icon: Grid3X3 },
  { id: 'admin-account-inventory', label: 'adminNav.accountInventory', path: '/admin/account-inventory', icon: PackageOpen },
  { id: 'admin-assigned-accounts', label: 'adminNav.assignedAccounts', path: '/admin/assigned-accounts', icon: KeyRound },
  { id: 'admin-entitlements', label: 'adminNav.entitlements', path: '/admin/entitlements', icon: Shield },
  { id: 'admin-pricing', label: 'adminNav.pricing', path: '/admin/pricing', icon: BadgeDollarSign },
  { id: 'admin-coupons', label: 'adminNav.coupons', path: '/admin/coupons', icon: Percent },
  { id: 'admin-warranty', label: 'adminNav.warranty', path: '/admin/warranty', icon: ShieldCheck },
  { id: 'admin-content', label: 'adminNav.content', path: '/admin/content', icon: Newspaper },
  { id: 'admin-settings', label: 'adminNav.settings', path: '/admin/settings', icon: Settings },
]
